# Generated by Django 3.2.4 on 2022-03-26 06:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220321_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('Present', models.IntegerField()),
                ('Violations', models.IntegerField()),
                ('Absent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('workers', models.IntegerField()),
                ('Contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('Present', models.IntegerField()),
                ('Violations', models.IntegerField()),
                ('Absent', models.IntegerField()),
                ('Contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contractor')),
                ('Project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
