# Generated by Django 3.2.4 on 2022-03-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220326_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='Absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Violations',
            field=models.IntegerField(default=0),
        ),
    ]
