# Generated by Django 3.2.4 on 2022-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='Past_Project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
