# Generated by Django 3.2.4 on 2022-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_worker_aadhaar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
