# Generated by Django 3.2.4 on 2022-03-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Contractor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Project',
            field=models.IntegerField(),
        ),
    ]
